###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: "3.1"
services:

    mysql:
      image: mysql:5.7
      container_name: myproject-mysql
      working_dir: /application
      volumes:
        - ./mysql:/application/mysql
      environment:
        - MYSQL_ROOT_PASSWORD=root
        - MYSQL_DATABASE=myproject
        - MYSQL_USER=dbuser
        - MYSQL_PASSWORD=123456
      ports:
        - "8082:3306"

    webserver:
      image: nginx:alpine
      container_name: myproject-webserver
      working_dir: /application
      volumes:
          - ./:/application
          - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      links:
        - php-fpm1
        - php-fpm2
        - redis
      ports:
       - "8080:80"

    php-fpm1:
      build: phpdocker/php-fpm
      container_name: "backend1"
      working_dir: /application
      environment:
        - BACKEND_NAME=BACKEND_1
      volumes:
        - ./:/application
        - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.2/fpm/conf.d/99-overrides.ini

    php-fpm2:
      build: phpdocker/php-fpm
      container_name: "backend2"
      working_dir: /application
      environment:
        - BACKEND_NAME=BACKEND_2
      volumes:
        - ./:/application
        - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.2/fpm/conf.d/99-overrides.ini

    pma:
      image: phpmyadmin/phpmyadmin:latest
      container_name: myproject-pma
      environment:
        - MYSQL_ROOT_PASSWORD=root
        - MYSQL_USER=dbuser
        - MYSQL_PASSWORD=dbuser
        - PMA_HOST=mysql
      ports:
        - "8090:80"
    
    redis:
      image: redis:alpine
      container_name: myproject-redis
